import { Campus } from "./types2";

export const campus: Campus = {
  id: "alu",
  type: "campus",
  buildings: [
    {
      type: "building",
      id: "social",
      name: "Social Commons",
      floors: [
        {
          type: "floor",
          id: "ground",
          level: 0,
          path: [
            [0, 0],
            [400, 0],
            [400, 200],
            [600, 200],
            [600, 300],
            [200, 300],
            [200, 100],
            [0, 100],
          ],
          spaces: [
            {
              id: "leadership-centre",
              type: "space",
              name: "Leadership Center",
              spaceType: "open",
              path: [
                [200, 120],
                [280, 120],
                [280, 200],
                [400, 200],
                [400, 300],
                [200, 300],
              ],
            },
            {
              id: "class-benin",
              type: "space",
              name: "Benin",
              subType: "classroom",
              position: [0, 0],
              size: [100, 100],
            },
            {
              id: "class-eswatini",
              type: "space",
              subType: "classroom",
              name: "Eswatini",
              position: [500, 200],
              size: [100, 100],
            },
            {
              id: "office-1",
              type: "space",
              name: "Office 1",
              subType: "office",
              position: [200, 50],
              size: [50, 50],
            },
            {
              id: "office-2",
              type: "space",
              name: "Office 2",
              subType: "office",
              position: [250, 50],
              size: [50, 50],
            },
            {
              id: "relaxation-room",
              type: "space",
              subType: "wellness",
              name: "Relaxation Room",
              position: [350, 100],
              size: [50, 33],
            },
            {
              id: "wellness-center",
              type: "space",
              name: "Wellness Center",
              subType: "wellness",
              position: [350, 133],
              size: [50, 66],
            },
            {
              id: "toilets",
              type: "space",
              name: "Toilets",
              subType: "toilet",
              position: [350, 0],
              size: [50, 100],
            },
          ],
          walls: [
            {
              id: "wall-1",
              type: "wall",
              name: "Wall of Leadership Center",
              path: [
                [300, 200],
                [320, 200],
              ],
            },
          ],
        },
        {
          type: "floor",
          id: "first",
          offset: [600, -100], // Rotated offset
          level: 1,
          path: [
            [-100, 0],
            [-100, 100],
            [-200, 100],
            [-200, 200],
            [-100, 200],
            [0, 200],
            [0, 400],
            [-400, 400],
            [-400, 200],
            [-600, 200],
            [-600, 0],
          ],
          spaces: [
            {
              id: "class-guinea",
              type: "space",
              name: "Guinea",
              subType: "classroom",
              position: [-100, 0],
              size: [-100, 100],
            },
            {
              id: "class-mozambique",
              type: "space",
              name: "Mozambique",
              subType: "classroom",
              position: [0, 200],
              size: [-100, 100],
            },
            {
              id: "class-malawi",
              type: "space",
              name: "Malawi",
              subType: "classroom",
              position: [0, 300],
              size: [-100, 100],
            },
            {
              id: "class-gambia",
              type: "space",
              name: "Gambia",
              subType: "classroom",
              position: [-500, 0],
              size: [-100, 100],
            },
            {
              id: "class-liberia",
              type: "space",
              name: "Liberia",
              subType: "classroom",
              position: [-500, 100],
              size: [-100, 100],
            },
            {
              id: "toilets-first",
              type: "space",
              name: "Toilets",
              subType: "toilet",
              position: [-200, 80],
              size: [-50, 140],
            },
            {
              id: "resource-center",
              type: "space",
              name: "Resource Center",
              subType: "library",
              position: [-300, 0],
              size: [-100, 100],
            },
          ],
          walls: [
            {
              id: "wall-liberia",
              type: "wall",
              name: "Wall in front of Liberia",
              path: [
                [-400, 200],
                [-400, 120],
                [-420, 100],
              ],
            },
            {
              id: "wall-leadership-center",
              type: "wall",
              name: "Wall that separates leadership center",
              path: [
                [-120, 340],
                [-300, 340],
                [-300, 180],
                [-320, 180],
              ],
            },
            {
              id: "wall-mozambique",
              type: "wall",
              name: "Wall in front of Mozambique",
              path: [
                [-200, 250],
                [-200, 340],
              ],
            },
            {
              id: "wall-malawi",
              type: "wall",
              name: "Wall in front of Malawi",
              path: [
                [-120, 360],
                [-120, 400],
              ],
            },
          ],
          holes: [
            {
              id: "hole-malawi",
              type: "hole",
              name: "Hole on top of Malawi",
              path: [
                [-120, 340],
                [-120, 400],
                [-400, 400],
                [-400, 200],
                [-300, 200],
                [-300, 340],
              ],
            },
            {
              id: "hole-liberia",
              type: "hole",
              name: "Hole in front of Liberia",
              path: [
                [-420, 100],
                [-400, 120],
                [-400, 200],
                [-500, 200],
                [-500, 100],
              ],
            },
          ],
        }
      ],
      stairs: [
        {
          id: "stair-benin",
          type: "stair",
          name: "Stairs in front of Benin",
          position: [150, 0],
          length: 80,
          floors: [0, 1],
        },
        {
          id: "stair-leadership",
          type: "stair",
          name: "Stairs in Leadership Center",
          position: [280, 120],
          length: 80,
          floors: [0, 1],
        },
        {
          id: "stair-eswatini",
          type: "stair",
          name: "Stairs in front of Eswatini",
          position: [400, 240],
          orientation: "horizontal",
          length: 80,
          floors: [0, 1],
        },
        // {
        //   id: "stair-malawi",
        //   type: "stair",
        //   name: "Stairs in front of Malawi",
        //   position: [340, 120],
        //   length: 80,
        //   floors: [1, 2],
        // },
        // {
        //   id: "stair-reception",
        //   type: "stair",
        //   name: "Stairs to reception",
        //   position: [100, 320],
        //   length: 80,
        //   orientation: "horizontal",
        //   floors: [1, 2],
        // },
        // {
        //   id: "stair-to-benin",
        //   type: "stair",
        //   name: "Stairs to Benin",
        //   position: [100, 440],
        //   length: 80,
        //   orientation: "horizontal",
        //   floors: [1, 2],
        // },
      ],
    },
  ],
};
