import { Campus } from "./types2";

export const campus: Campus = {
  id: "alu",
  type: "campus",
  buildings: [
    {
      type: "building",
      id: "social",
      name: "Social Commons",
      floors: [
        {
          type: "floor",
          id: "ground",
          level: 0,
          path: [
            [0, 0],
            [400, 0],
            [400, 200],
            [600, 200],
            [600, 300],
            [200, 300],
            [200, 100],
            [0, 100],
          ],
          spaces: [
            {
              id: "leadership-centre",
              type: "space",
              name: "Leadership Center",
              spaceType: "open",
              path: [
                [200, 120],
                [280, 120],
                [280, 200],
                [400, 200],
                [400, 300],
                [200, 300],
              ],
            },
            {
              id: "class-benin",
              type: "space",
              name: "Benin",
              subType: "classroom",
              position: [0, 0],
              size: [100, 100],
            },
            {
              id: "class-eswatini",
              type: "space",
              subType: "classroom",
              name: "Eswatini",
              position: [500, 200],
              size: [100, 100],
            },
            {
              id: "office-1",
              type: "space",
              name: "Office 1",
              subType: "office",
              position: [200, 50],
              size: [50, 50],
            },
            {
              id: "office-2",
              type: "space",
              name: "Office 2",
              subType: "office",
              position: [250, 50],
              size: [50, 50],
            },
            {
              id: "relaxation-room",
              type: "space",
              subType: "wellness",
              name: "Relaxation Room",
              position: [350, 100],
              size: [50, 33],
            },
            {
              id: "wellness-center",
              type: "space",
              name: "Wellness Center",
              subType: "wellness",
              position: [350, 133],
              size: [50, 66],
            },
            {
              id: "toilets",
              type: "space",
              name: "Toilets",
              subType: "toilet",
              position: [350, 0],
              size: [50, 100],
            },
          ],
          walls: [
            {
              id: "wall-1",
              type: "wall",
              name: "Wall of Leadership Center",
              path: [
                [300, 200],
                [320, 200],
              ],
            },
          ],
        },
      ],
      stairs: [
        {
          id: "stair-benin",
          type: "stair",
          name: "Stairs in front of Benin",
          position: [150, 0],
          length: 80,
          floors: [0, 1],
        },
        {
          id: "stair-leadership",
          type: "stair",
          name: "Stairs in Leadership Center",
          position: [280, 120],
          length: 80,
          floors: [0, 1],
        },
        {
          id: "stair-eswatini",
          type: "stair",
          name: "Stairs in front of Eswatini",
          position: [400, 240],
          orientation: "horizontal",
          length: 80,
          floors: [0, 1],
        },
      ],
    },
  ],
};
